services:
  # Web Service Unificado (Frontend Vite + Backend Spring Boot en un solo contenedor)
  - type: web
    name: siga-veterinaria
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false # Ej: jdbc:mysql://host:3306/siga_db?useSSL=true&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SIGA_JWT_SECRET
        generateValue: true
      - key: JAVA_TOOL_OPTIONS
        value: "-Xms128m -Xmx384m -XX:+UseG1GC"
